theme = "gruvbox-material"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
true-color = true
text-width = 120
color-modes = true
popup-border = "all"
bufferline = "always"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = false
display-signature-help-docs = true
snippets = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator","version-control", "file-modification-indicator"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1000

[editor.indent-guides]
render = true
character = "‚ñè"

[editor.soft-wrap]
enable = true
wrap-indicator = ""
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
C-h = "goto_line_start"
C-l = "goto_line_end_newline"

[keys.normal.g]
x = ":buffer-close"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
