"attribute" = { fg = "purple", modifiers = ["italic"] }
"type" = "orange"
"type.builtin" = "yellow"
"constructor" = { fg = "green", modifiers = ["bold"] }
"constant" = "fg0"
"constant.builtin" = { fg = "purple", modifiers = ["italic"] }
"constant.builtin.boolean" = "purple"
"constant.character.escape" = "green"
"string" = "aqua"
"string.regexp" = "green"
"string.special" = "yellow"
"comment" = { fg = "grey1", modifiers = ["italic"] }
"variable" = "fg0"
"variable.builtin" = { fg = "purple", modifiers = ["italic"] }
"variable.other.member" = "blue"
"label" = "orange"
"punctuation" = "grey2"
"punctuation.special" = "blue"
"keyword" = { fg = "red", modifiers = ["italic"] }
"keyword.operator" = "orange"
"keyword.directive" = "purple"
"operator" = "orange"
"function" = { fg = "green", modifiers = ["bold"] }
"tag" = "orange"
"namespace" = { fg = "yellow", modifiers = ["italic"] }
"module" = "yellow"
"special" = "blue"

"markup.heading.marker" = "grey1"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", underline = { style = "line" } }
"markup.link.label" = "orange"
"markup.link.text" = "purple"
"markup.quote" = "grey1"
"markup.raw.inline" = "green"
"markup.raw.block" = "aqua"

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

"ui.background" = { fg = "grey1", bg = "bg0" }
"ui.background.separator" = "grey0"
"ui.cursor" = { fg = "bg1", bg = "grey0" }
"ui.cursor.primary" = { fg = "bg0", bg = "fg0" }
"ui.cursor.primary.insert" = { fg = "bg0", bg = "green" }
"ui.cursor.primary.select" = { fg = "bg0", bg = "red" }
"ui.cursor.match" = { fg = "fg0", bg = "bg5" }
"ui.gutter" = { bg = "bg0" }
"ui.gutter.selected" = { bg = "bg1" }
"ui.linenr" = "bg5"
"ui.linenr.selected" = { fg = "grey1", bg = "bg1" }
"ui.statusline" = { fg = "fg1", bg = "bg_statusline1" }
"ui.statusline.inactive" = { fg = "grey1", bg = "bg_statusline1" }
"ui.statusline.normal" = { fg = "bg0", bg = "grey2", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "bg0", bg = "bg_green", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "bg0", bg = "bg_red", modifiers = ["bold"] }
"ui.popup" = { fg = "fg1", bg = "bg3" }
"ui.window" = "grey0"
"ui.help" = { fg = "fg1", bg = "bg3" }
"ui.text" = "fg0"
"ui.text.focus" = { fg = "green", modifiers = ["bold"] }
"ui.text.inactive" = "bg4"
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.inlay-hint" = { fg = "grey0" }
"ui.virtual.wrap" = { fg = "grey0" }
"ui.menu" = { fg = "fg1", bg = "bg3" }
"ui.menu.selected" = { fg = "bg3", bg = "bg_green" }
"ui.selection" = { bg = "bg3" }
"ui.selection.primary" = { bg = "bg_visual_green" }
"ui.highlight" = { bg = "bg_diff_green" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.bufferline" = { fg = "fg1", bg = "bg_statusline3" }
"ui.bufferline.active" = { fg = "bg0", bg = "grey2", modifiers = [
  "bold",
] }
"ui.bufferline.background" = { bg = "bg_statusline1" }

"warning" = "yellow"
"error" = "red"
"info" = "blue"
"hint" = "green"

"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]

# background dark hard

"bg_dim" = "#141617"
"bg0" = "#1d2021"
"bg1" = "#282828"
"bg2" = "#282828"
"bg3" = "#3c3836"
"bg4" = "#3c3836"
"bg5" = "#504945"
"bg_statusline1" = "#282828"
"bg_statusline2" = "#32302f"
"bg_statusline3" = "#504945"
"bg_diff_green" = "#32361a"
"bg_visual_green" = "#333e34"
"bg_diff_red" = "#3c1f1e"
"bg_visual_red" = "#442e2d"
"bg_diff_blue" = "#0d3138"
"bg_visual_blue" = "#2e3b3b"
"bg_visual_yellow" = "#473c29"
"bg_current_word" = "#32302f"

# foreground dark material

"fg0" = "#d4be98"
"fg1" = "#ddc7a1"
"red" = "#ea6962"
"orange" = "#e78a4e"
"yellow" = "#d8a657"
"green" = "#a9b665"
"aqua" = "#89b482"
"blue" = "#7daea3"
"purple" = "#d3869b"
"bg_red" = "#ea6962"
"bg_green" = "#a9b665"
"bg_yellow" = "#d8a657"

# foreground dark

"grey0" = "#7c6f64"
"grey1" = "#928374"
"grey2" = "#a89984"
